<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Font Awesome -->
    <link href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" rel="stylesheet">

    <!-- Bootstrap CSS e JSs -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>

<body style="background-color: rgb(247, 189, 189);">

    <div align="center">
        <table class="head-wrap w320 full-width-gmail-android" bgcolor="#f9f8f8" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <td class="bg-dark w-100">

                    <div height="8">
                    </div>

                </td>
            </tr>
            <tr class="bg-dark">
                <td class="header container" align="center">
                    <div class="content">
                        <span class="brand">
                            <a href="http://onlieat.epizy.com">
                                <h1 class="text-light h1">Onli<strong class="text-danger">Eat</strong>
                                    <a href="/"><i class="fas fa-utensils text-white"></i></a>
                                </h1>
                            </a>
                        </span>
                    </div>
                </td>
            </tr>
        </table>

        <table class="body-wrap w320">
            <tr>
                <td></td>
                <td class="container">
                    <div class="content">
                        <table cellspacing="0">
                            <tr>
                                <td>
                                    <table class="soapbox">
                                        <tr>
                                            <td class="soapbox-title">Recuperação de Senha</td>
                                        </tr>
                                    </table>
                                    <table class="body">
                                        <tr>
                                            <td class="body-padding"></td>
                                            <td class="body-padded">
                                                <div class="body-title">Olá, <?= $this->view->name ?></div>
                                                <table class="body-text">
                                                    <tr>
                                                        <td class="body-text-cell">
                                                            Para redefinir a sua senha acesse o link <a href="<?= $this->view->link ?>"><?= $this->view->link ?></a>.
                                                        </td>
                                                    </tr>
                                                </table>
                                                <div>
                                                    <a href="<?= $this->view->link ?>" class="btn btn-dark text-white shadow">
                                                        Redefinir Senha
                                                    </a>
                                                </div>
                                                <table class="body-signature-block">
                                                    <tr>
                                                        <td class="body-signature-cell">
                                                            <p>Obrigado!</p>
                                                            <p class="body-signature"><span class="text-white">Onli</span><span class="text-danger">Eat</span>
                                                                <i class="fas fa-utensils text-white"></i>
                                                            </p>
                                                        </td>
                                                    </tr>
                                                </table>
                                            </td>
                                            <td class="body-padding"></td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                        </table>
                    </div>
                </td>
                <td></td>
            </tr>
        </table>

        <table class="footer-wrap w320 full-width-gmail-android" bgcolor="#e5e5e5">
            <tr>
                <td></td>
                <td class="container">
                    <div class="content footer-lead">
                        <a href="#"><b>Get in touch</b></a> if you have any questions or feedback
                    </div>
                </td>
                <td></td>
            </tr>
        </table>

    </div>

</body>

</html>