<style>
    @media (max-width: 575.98px) {
        .capa .btn-custom {
            margin: 10px 15px;
        }

        .capa .btn-custom {
            font-size: 1em;
        }
    }
</style>
<!-- Janela Modal -->
<div class="modal fade mt-5" id="modal-mensagem">
    <div class="modal-dialog">
        <div class="modal-content">

            <!-- Cadastro Modal Sucesso -->
            <?php if (isset($_GET['modal']) && $_GET['modal'] == "success") {
            ?>
                <div class="modal-header bg-dark d-flex justify-content-center ">
                    <h1 class="text-white h1  text-center">Onli<strong class="text-danger">Eat</strong>
                        <i class="fas fa-utensils"></i>
                    </h1>
                </div>
                <div class="modal-body">
                    <div class="ml-auto text-center">
                        <h3 class="text-success">Nós agradecemos você!</h3>
                        <p class="text-secondary">
                            Fique atendo, em breve te enviaremos promoções incríveis.
                        </p>
                    </div>

                </div>
                <div class="d-flex justify-content-center border-top">
                    <a class="text-secondary  my-3" href="" data-dismiss="modal" title="Fechar" alt="Close">Fechar</a>
                </div>
                <!-- Fim modal Sucesso -->
            <?php } else { ?>

                <!-- Modal Padrão -->
                <div class="modal-header bg-dark text-white">
                    <h4 class="modal-title ml-5 h4">Deseja receber nossas ofertas?</h4>
                    <button type="button" class="close text-white" data-dismiss="modal" title="Fechar" alt="Fechar">&times;</button>
                </div>
                <div class="modal-body text-white">
                    <div class="d-flex justify-content-center text-center">
                        <h1 class="text-secondary h1 align-self-lg-center text-center">Onli<strong class="text-danger">Eat</strong>
                            <i class="fas fa-utensils"></i>
                        </h1>
                    </div>

                    <!-- Mensagem de erro -->
                    <?php if (isset($_GET['modal']) && $_GET['modal'] == "error") {
                        echo "<div class='text-center'><h4 class='text-danger'>Erro, tente novamente!</h4></div>";
                    } ?>
                    <!-- Fim mensagem de erro -->

                    <!-- Formulário modal -->
                    <div class="ml-auto justify-content-sm-end justify-content-end">
                        <form action="formModal" method="POST" class="form">
                            <p class="p text-center text-dark">Preencha os campos abaixo</p>
                            <input type="text" name="cli_name" class="form-control mb-1" placeholder="Seu nome completo" required>
                            <input type="email" name="cli_email" class="form-control" placeholder="Digite seu e-mail" required>
                            <input type="text" name="cli_phone" class="form-control my-1" maxlength="13" onKeyPress="formata(this,'## #####-####')" placeholder="Digite seu celular">
                            <div class="d-flex justify-content-center">
                                <button type="submit" class="btn btn-dark w-100">Enviar</button>
                            </div>
                        </form>
                    </div>
                    <!-- Fim form modal -->
                    <hr>

                    <!-- Botão close Padrão -->
                    <div class="d-flex justify-content-center">
                        <a class="text-secondary" href="" data-dismiss="modal" title="Não obrigado" alt="Close">Não, obrigado</a>
                    </div>
                    <!-- Fim botão -->
                    <!-- Encerramento Modal Padrão -> Else -->
                <?php } ?>
                </div> <!-- Fim body janela modal padrão-->
        </div> <!-- Fim da janela modal -->
    </div>
</div>
<!--Capa-->
<section id="capa" class="my-5">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 p-0">
                <div class="d-flex justify-content-center p-0">

                    <!--Carousel Wrapper-->
                    <div id="carousel-example-1z" class="carousel slide" role="listbox" data-ride="carousel">
                        <!--Indicators-->
                        <ol class="carousel-indicators">
                            <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
                            <li data-target="#carousel-example-1z" data-slide-to="1"></li>
                        </ol>
                        <!--/.Indicators-->
                        <!--Slides-->
                        <div class="carousel-inner" role="listbox">
                            <!--First slide-->
                            <div class="carousel-item active">
                                <img class="d-block w-100" src="Public/img/img-carousell-02.png" alt="First slide">
                                <br>
                            </div>
                            <!--/First slide-->
                            <!--Second slide-->
                            <div class="carousel-item">
                                <img class="d-block w-100" src="Public/img/img-carousell-03.png" alt="Second slide">
                                <div class="carousel-caption align-content-center">
                                    <h3 class="text-secondary d-none d-md-block">
                                        Faça seu pedido agora mesmo!
                                    </h3>
                                    <br>
                                    <a href="\menu_digital" class="buttonSlide btn btn-danger">
                                        Cardápio
                                    </a>
                                </div>
                            </div>
                            <!--/Second slide-->
                        </div>
                        <!--/.Slides-->
                        <!--Controls-->
                        <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                        <!--/.Controls-->
                    </div>
                    <!--/.Carousel Wrapper-->
                </div>
            </div>
        </div>
    </div>
</section>
<!--Fim Capa-->

<!-- Cardápio -->
<section id="cardapio" class="mb-0 py-5 bg-dark">
    <div class="container-fluid">
        <div class="row d-flex justify-content-center">

            <div class="col-sm-12 col-md-6">

                <div class="row px-5">
                    <h3 class="h3 text-white text-center">
                        Feito para todas as plataformas
                    </h3>
                    <div class="h5 d-none d-lg-block text-white text-center">
                        Compuladores, Tablets e Celulares
                    </div>
                </div>

                <hr class="bg-light">

                <div class="row px-5">
                    <div class="mx-5">
                        <img src="Public/img/dispositivos.png" title="Dispositivos" width="350" height="350" class="img-fluid">
                    </div>
                </div>
                <div class="row px-5">
                    <div class="mx-5">
                        <a class="btn btn-outline-danger btn-lg mb-5" href="\menu_digital">Cardápio digital</a>
                    </div>
                </div>

            </div>

            <div class="col-sm-12 col-md-6">
                <div class="row px-5">
                    <h3 class="h3 text-white text-center">
                        Nossos produtos são classificados em categoria
                    </h3>
                </div>
                <hr class="hr bg-light">
                <div class="row products px-5">
                    <ul class="list-unstyled mt-3">
                        <li class="media py-2">
                            <img src="Public/img/lanches.png" title="Lanches" class="img-fluid w-25">
                            <div class="media-body ml-2">
                                <h4 class="text-danger">Os mais delíciosos lanches</h4>
                                <p class="mb-0 text-secondary">
                                    Ao selecionar a categoria lanches, você terá uma lista de vários lanches deliciosos com ótimos preços.
                                </p>
                            </div>
                        </li>
                        <li class="media py-2">
                            <img src="Public/img/porcoes.png" title="Porções" class="img-fluid w-25">
                            <div class="media-body ml-2">
                                <h4 class="text-danger">Várias porções muito saborosas</h4>
                                <p class="mb-0 text-secondary">
                                    Ao selecionar a categoria porções, você terá uma lista de várias porções deliciosas com ótimos preços.
                                </p>
                            </div>
                        </li>
                        <li class="media py-2">
                            <img src="Public/img/bebidas.png" title="Bebidas" class="img-fluid w-25">
                            <div class="media-body ml-2">
                                <h4 class="text-danger">Bebidas geladinhas pra você</h4>
                                <p class="mb-0 text-secondary">
                                    Ao selecionar a categoria bebidas, você terá uma lista de várias bebidas geladinhas com ótimos preços.
                                </p>
                            </div>
                        </li>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Cardápio -->
<!-- Sobre -->
<section id="sobre" class="mt-0 py-5 bg-white">
    <div class="container">
        <div class="row">
            <div class="col-12 p-5">
                <h2 class="border-bottom h2 text-dark p-2 text-center">Desenvolvedores</h2>
                <ul class="list-unstyled mt-3">
                    <li class="media border-bottom py-2">
                        <img class="my-1 mr-2 align-self-center img-fluid rounded-circle" title="Aluno" width="130" height="130" src="Public/img/robson.jpg">
                        <div class="media-body ml-2">
                            <h4 class="text-dark">Robson Batista Solano</h4>
                            <p class="mb-0 text-secondary">
                                Aluno do curso de Analise e Desenvolvimento de Sistemas
                            </p>
                            <p class="mb-0 text-secondary">
                                Projeto interdisciplinar - 4º semestre - Cruzeiro do sul / Ceunsp - Salto
                            </p>
                        </div>
                    </li>
                    <li class="media py-2">
                        <img class="my-1 mr-2 align-self-center img-fluid rounded-circle" title="Aluno" width="130" height="130" src="Public/img/matheus.jpeg">
                        <div class="media-body ml-2">
                            <h4 class="text-dark">Matheus Melquídes dos Anjos</h4>
                            <p class="mb-0 text-secondary">
                                Aluno do curso de Analise e Desenvolvimento de Sistemas
                            </p>
                            <p class="mb-0 text-secondary">
                                Projeto interdisciplinar - 4º semestre - Cruzeiro do sul / Ceunsp - Salto
                            </p>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</section><!-- Fim Sobre-->