<div class="container">
    <div class="row">
        <div class="col-12 text-center">
            <h3 class="text-danger">
                Manutenção!
            </h3>
            <p class="text-dark">
                Lamentamos o transtorno, mas estamos trabalhando para melhorar sua experiência com nosso sistema.<br> Agradecemos sua conpreensão
            </p>
        </div>
    </div>
</div>
<?php echo '<meta http-equiv="refresh" content="8;/">'; ?>